version: "3.7"
services:
  personal-finance:
    build: .
    container_name: personal-finance
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - personal-finance-network

  db:
    image: mysql:latest
    container_name: personal-finance-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - personal-finance-network

  nginx:
    image: nginx:alpine
    container_name: personal-finance-nginx
    restart: unless-stopped
    ports:
#      - 8000:80
       - 80:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - personal-finance-network

networks:
  personal-finance-network:
    driver: bridge

volumes:
  mysql-data:
